name: Ironclad
favicon: null
layout_spectrum: 0.11844729026779532
typography_spectrum: 0.527719036443159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6431801666039973
  lightness: 0.5583032967988402
  saturation: 0.11993605922907591
  rhythmicContrast: 0.5651077260263264
purpose: []
